[package]
name = "storyteller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = "0.9.2"
num = "0.4.1"
walkdir = "2.3.1"
colored = "2.0.4"